### ISSUE TITLE
커밋 테스트

### ISSUE THREAD

**Issue by thyoondev** [INFP-Study/React-Springboot-INFPStudy-ToyProjects#50]
## 미션
1. develop 브랜치 기준으로 clone or pull 받기
2. 본인팀 src -> pages -> index.js 파일에 글자 추가하기
3. 브랜치 생성 (ex : Alpha_frontend)
4. 파일 스테이징 후 커밋하기 (커밋에는 이슈번호 등록)
5. 원격 저장소에 푸시하기

**Comment by thyoondev** [comment]
완료했습니당~~

**Comment by k-sense** [comment]
완료했습니다

**Comment by chlwlgus4** [comment]
커밋 완료

**Comment by lseunghee** [comment]
커밋 완료

**Comment by nrudev** [comment]
완료했습니다

**Comment by HyeJeongIm** [comment]
커밋 완료 했습니다

**Comment by yeongunheo** [comment]
Alpha_backend_1에 커밋 완료했습니다!
